
#ifndef ITEM_OVERRIDE_H_
#define ITEM_OVERRIDE_H_

//None
#define ITEM_NONE 0

//Berries
#define ITEM_CHERI_BERRY 149
#define ITEM_CHESTO_BERRY 150
#define ITEM_PECHA_BERRY 151
#define ITEM_RAWST_BERRY 152
#define ITEM_ASPEAR_BERRY 153
#define ITEM_LEPPA_BERRY 154
#define ITEM_ORAN_BERRY 155
#define ITEM_PERSIM_BERRY 156
#define ITEM_LUM_BERRY 157
#define ITEM_SITRUS_BERRY 158
#define ITEM_FIGY_BERRY 159
#define ITEM_WIKI_BERRY 160
#define ITEM_MAGO_BERRY 161
#define ITEM_AGUAV_BERRY 162
#define ITEM_IAPAPA_BERRY 163
#define ITEM_RAZZ_BERRY 164
#define ITEM_BLUK_BERRY 165
#define ITEM_NANAB_BERRY 166
#define ITEM_WEPEAR_BERRY 167
#define ITEM_PINAP_BERRY 168
#define ITEM_POMEG_BERRY 169
#define ITEM_KELPSY_BERRY 170
#define ITEM_QUALOT_BERRY 171
#define ITEM_HONDEW_BERRY 172
#define ITEM_GREPA_BERRY 173
#define ITEM_TAMATO_BERRY 174
#define ITEM_CORNN_BERRY 175
#define ITEM_MAGOST_BERRY 176
#define ITEM_RABUTA_BERRY 177
#define ITEM_NOMEL_BERRY 178
#define ITEM_SPELON_BERRY 179
#define ITEM_PAMTRE_BERRY 180
#define ITEM_WATMEL_BERRY 181
#define ITEM_DURIN_BERRY 182
#define ITEM_BELUE_BERRY 183
#define ITEM_OCCA_BERRY 184
#define ITEM_PASSHO_BERRY 185
#define ITEM_WACAN_BERRY 186
#define ITEM_RINDO_BERRY 187
#define ITEM_YACHE_BERRY 188
#define ITEM_CHOPLE_BERRY 189
#define ITEM_KEBIA_BERRY 190
#define ITEM_SHUCA_BERRY 191
#define ITEM_COBA_BERRY 192
#define ITEM_PAYAPA_BERRY 193
#define ITEM_TANGA_BERRY 194
#define ITEM_CHARTI_BERRY 195
#define ITEM_KASIB_BERRY 196
#define ITEM_HABAN_BERRY 197
#define ITEM_COLBUR_BERRY 198
#define ITEM_BABIRI_BERRY 199
#define ITEM_CHILAN_BERRY 200
#define ITEM_LIECHI_BERRY 201
#define ITEM_GANLON_BERRY 202
#define ITEM_SALAC_BERRY 203
#define ITEM_PETAYA_BERRY 204
#define ITEM_APICOT_BERRY 205
#define ITEM_LANSAT_BERRY 206
#define ITEM_STARF_BERRY 207
#define ITEM_ENIGMA_BERRY 208
#define ITEM_MICLE_BERRY 209
#define ITEM_CUSTAP_BERRY 210
#define ITEM_JABOCA_BERRY 211
#define ITEM_ROWAP_BERRY 212
#define ITEM_ROSELI_BERRY 686
#define ITEM_KEE_BERRY 687
#define ITEM_MARANGA_BERRY 688

//Plates
#define ITEM_FLAME_PLATE 298
#define ITEM_SPLASH_PLATE 299
#define ITEM_ZAP_PLATE 300
#define ITEM_MEADOW_PLATE 301
#define ITEM_ICICLE_PLATE 302
#define ITEM_FIST_PLATE 303
#define ITEM_TOXIC_PLATE 304
#define ITEM_EARTH_PLATE 305
#define ITEM_SKY_PLATE 306
#define ITEM_MIND_PLATE 307
#define ITEM_INSECT_PLATE 308
#define ITEM_STONE_PLATE 309
#define ITEM_SPOOKY_PLATE 310
#define ITEM_DRACO_PLATE 311
#define ITEM_DREAD_PLATE 312
#define ITEM_IRON_PLATE 313
#define ITEM_PIXIE_PLATE 644

//Gems
#define ITEM_FIRE_GEM 548
#define ITEM_WATER_GEM 549
#define ITEM_ELECTRIC_GEM 550
#define ITEM_GRASS_GEM 551
#define ITEM_ICE_GEM 552
#define ITEM_FIGHTING_GEM 553
#define ITEM_POISON_GEM 554
#define ITEM_GROUND_GEM 555
#define ITEM_FLYING_GEM 556
#define ITEM_PSYCHIC_GEM 557
#define ITEM_BUG_GEM 558
#define ITEM_ROCK_GEM 559
#define ITEM_GHOST_GEM 560
#define ITEM_DRAGON_GEM 561
#define ITEM_DARK_GEM 562
#define ITEM_STEEL_GEM 563
#define ITEM_NORMAL_GEM 564
#define ITEM_FAIRY_GEM 715

#endif /* ITEM_OVERRIDE_H_ */
