#ifndef MOVE_CHAIN_STATES_H_
#define MOVE_CHAIN_STATES_H_

enum RunDecisionStates {
    S_RUN_SWITCH = 0,
    S_RUN_AFTER_SWITCH,
    S_RUN_SWITCH_ALTERNATE_BANK,
    S_RUN_MOVE,
    S_RUN_MOVE_ALTERNATE_BANK,
    S_UPDATE_TURN_CALLBACKS,
    S_SOFT_RESET_BANK,
    S_END_BATTLE,

};

enum RunFaintStates {
    S_CHECK_BANK1_FAINT = 0,
    S_CHECK_BANK2_FAINT,
    S_RESOLVE_FAINTS,
};


enum RunFleeStates {
    S_CHECK_FLEEING = 0,
    S_NOT_FLEEING,
    S_TRY_FLEE,
};


enum RunSwitchStates {
    S_RUN_FLEE = 0,
    S_RUN_SWITCH_CHECKS,
    S_SWITCH_LOGIC,
};

enum RunMoveStates {
    S_BEFORE_MOVE = 0,
    S_BEFORE_MOVE_RESOLUTION,
    S_CONFIG_MOVE_EXEC,
    S_RUN_MOVE_HIT,
    S_MOVE_FAILED,
    S_RUN_FAINT,
    S_RESIDUAL_MOVES,
    S_WAIT_HPUPDATE_RUN_MOVE,
};

enum MoveHitStates {
    S_MOVE_TRYHIT = 0,
    S_GENERAL_TRYHIT,
    S_DAMAGE_CALC_AND_APPLY,
    S_HEAL_CALC_AND_APPLY,
    S_MOVE_EFFECT,
    S_RECOIL_APPLY,
    S_DRAIN_APPLY,
    S_SECONDARY_ROLL_CHANCE,
    S_SECONDARY_ROLL_AILMENTS,
    S_SECONDARY_ON_HIT,
    S_AFTER_MOVE_SECONDARY,
    S_AFTER_MOVE,
};


#endif /* MOVE_CHAIN_STATES_H_ */
